"""
One-shot script: set passwords for origo_app and origo_admin roles.

Run via Railway (uses the superuser DATABASE_URL injected by Railway):
    railway run --service origo-api python scripts/setup_db_roles.py

The two passwords are read from env vars so they never appear in shell history:
    $env:APP_PW    = "some-strong-password"
    $env:ADMIN_PW  = "another-strong-password"
    railway run --service origo-api python scripts/setup_db_roles.py
"""
import os
import urllib.parse
import asyncio

import asyncpg


async def main() -> None:
    db_url = os.environ["DATABASE_URL"]
    app_pw = os.environ.get("APP_PW")
    admin_pw = os.environ.get("ADMIN_PW")

    if not app_pw or not admin_pw:
        raise SystemExit(
            "Set APP_PW and ADMIN_PW environment variables before running.\n"
            "  $env:APP_PW   = '<strong-random-password>'\n"
            "  $env:ADMIN_PW = '<another-strong-password>'"
        )

    # asyncpg needs postgresql:// not postgresql+asyncpg://
    url = db_url.replace("postgresql+asyncpg://", "postgresql://").replace("postgres://", "postgresql://")

    print(f"Connecting to DB...")
    conn = await asyncpg.connect(url)

    try:
        # Set passwords — ALTER ROLE does not support $1 parameters; embed directly.
        # The passwords are generated by this script, not user-supplied, so this is safe.
        escaped_app = app_pw.replace("'", "''")
        escaped_admin = admin_pw.replace("'", "''")
        await conn.execute(f"ALTER ROLE origo_app   PASSWORD '{escaped_app}'")
        await conn.execute(f"ALTER ROLE origo_admin PASSWORD '{escaped_admin}'")
        print("Passwords set.")

        # Verify
        rows = await conn.fetch(
            "SELECT rolname, rolcanlogin, rolbypassrls "
            "FROM pg_roles WHERE rolname IN ('origo_app', 'origo_admin') "
            "ORDER BY rolname"
        )
        for r in rows:
            print(f"  {r['rolname']}: login={r['rolcanlogin']} bypassrls={r['rolbypassrls']}")

        # Smoke test: RLS must block all rows when no client_id is set
        # Connect as origo_app to verify
        host_parsed = urllib.parse.urlparse(url)
        app_url = host_parsed._replace(
            netloc=f"origo_app:{urllib.parse.quote(app_pw)}@{host_parsed.hostname}:{host_parsed.port or 5432}"
        ).geturl()
        app_conn = await asyncpg.connect(app_url)
        try:
            count = await app_conn.fetchval("SELECT COUNT(*) FROM runs")
            if count == 0:
                print("RLS smoke test PASSED — 0 rows visible to origo_app without client_id set.")
            else:
                print(f"RLS smoke test FAILED — {count} rows visible (RLS may not be enforced).")
        except Exception as e:
            print(f"RLS smoke test error: {e}")
        finally:
            await app_conn.close()

        # Print the connection strings the user needs to copy into Railway
        parsed = urllib.parse.urlparse(url)
        host = parsed.hostname
        port = parsed.port or 5432
        dbname = parsed.path.lstrip("/")

        print("\n--- Copy these into Railway env vars ---")
        print(f"DATABASE_URL_ADMIN=postgresql+asyncpg://origo_admin:{urllib.parse.quote(admin_pw)}@{host}:{port}/{dbname}")
        print(f"DATABASE_URL_APP=postgresql+asyncpg://origo_app:{urllib.parse.quote(app_pw)}@{host}:{port}/{dbname}")
        print("----------------------------------------")

    finally:
        await conn.close()


asyncio.run(main())
