"""
Scheduler service — arq job functions.

scheduler_tick: cron job running every minute.  Evaluates all active scheduled
    clients and enqueues execute_scheduled_run for any that are due.

execute_scheduled_run: arq job that runs the pipeline for one client.
    Called by scheduler_tick; uses the same run_pipeline() as manual triggers.
"""
import uuid
from datetime import datetime, timezone

def _now() -> datetime:
    """Current time as naive UTC — safe for TIMESTAMP WITHOUT TIME ZONE columns."""
    return datetime.now(timezone.utc).replace(tzinfo=None)

import structlog
from arq import Retry
from sqlalchemy import select

from app.db import AsyncSessionLocal
from app.models.client import Client
from app.models.scheduler_health import SchedulerHealth
from app.models.scheduler_run import SchedulerRun
from app.services.audit_service import log_audit
from app.services.pipeline import run_pipeline
from app.services.run_orchestrator import start_run
from app.services.schedule_service import is_due_to_run, update_next_run_time
from app.services.scheduler_alerts import check_and_alert_on_failures, check_stale_clients

logger = structlog.get_logger()


async def scheduler_tick(ctx: dict) -> dict:
    """
    arq cron job — fires every minute.
    Evaluates all schedule-enabled active clients and enqueues runs for those due.
    """
    start_time = _now()
    tick_id = str(uuid.uuid4())[:8]
    log = logger.bind(tick_id=tick_id)
    log.info("scheduler_tick_start")

    clients_evaluated = 0
    runs_enqueued = 0

    try:
        # Load candidate clients (coarse filter — fine filter is is_due_to_run)
        async with AsyncSessionLocal() as db:
            candidates = (
                await db.execute(
                    select(Client).where(
                        Client.schedule_enabled.is_(True),
                        Client.status == "active",
                    )
                )
            ).scalars().all()

        for client in candidates:
            clients_evaluated += 1
            try:
                sr_id: uuid.UUID | None = None

                async with AsyncSessionLocal() as db:
                    async with db.begin():
                        # Lock the row to prevent concurrent tick double-fires
                        locked = (
                            await db.execute(
                                select(Client)
                                .where(Client.id == client.id)
                                .with_for_update(skip_locked=True)
                            )
                        ).scalar_one_or_none()

                        if locked is None:
                            continue  # Another worker tick holds the lock

                        if not await is_due_to_run(locked, start_time, db):
                            continue

                        # Create SchedulerRun record (UUID from Python default)
                        sr = SchedulerRun(
                            client_id=locked.id,
                            cadence=locked.schedule_cadence,
                            status="enqueued",
                            triggered_at=start_time,
                        )
                        db.add(sr)
                        sr_id = sr.id  # uuid4() generated by Python default

                        # Atomically advance next_scheduled_run_at before releasing lock
                        update_next_run_time(locked, start_time)
                        # Transaction auto-commits on context exit

                if sr_id is None:
                    continue

                # Enqueue outside the DB transaction
                await ctx["redis"].enqueue_job(
                    "execute_scheduled_run",
                    str(client.id),
                    str(sr_id),
                    _job_id=str(sr_id),  # idempotent job ID
                )
                runs_enqueued += 1
                log.info(
                    "run_enqueued",
                    client_id=str(client.id),
                    cadence=client.schedule_cadence,
                    sr_id=str(sr_id),
                )

            except Exception as exc:
                log.error("tick_client_error", client_id=str(client.id), error=str(exc))

        # Stale-client alerting (best-effort — don't fail the tick on alert errors)
        try:
            async with AsyncSessionLocal() as db:
                await check_stale_clients(db, start_time)
        except Exception:
            pass

        # Update health heartbeat
        duration_ms = int((_now() - start_time).total_seconds() * 1000)
        async with AsyncSessionLocal() as db:
            async with db.begin():
                health = (
                    await db.execute(
                        select(SchedulerHealth).where(SchedulerHealth.id == 1)
                    )
                ).scalar_one_or_none()
                if health:
                    health.last_tick_at = start_time
                    health.last_tick_duration_ms = duration_ms
                    health.last_tick_clients_evaluated = clients_evaluated
                    health.last_tick_runs_enqueued = runs_enqueued
                    health.consecutive_failures = 0
                    health.last_error = None
                    health.updated_at = _now()

        log.info(
            "scheduler_tick_complete",
            clients_evaluated=clients_evaluated,
            runs_enqueued=runs_enqueued,
            duration_ms=duration_ms,
        )
        return {"clients_evaluated": clients_evaluated, "runs_enqueued": runs_enqueued}

    except Exception as exc:
        log.error("scheduler_tick_failed", error=str(exc))

        try:
            async with AsyncSessionLocal() as db:
                async with db.begin():
                    health = (
                        await db.execute(
                            select(SchedulerHealth).where(SchedulerHealth.id == 1)
                        )
                    ).scalar_one_or_none()
                    if health:
                        health.consecutive_failures = (health.consecutive_failures or 0) + 1
                        health.last_error = str(exc)[:500]
                        health.updated_at = _now()
        except Exception:
            pass

        await check_and_alert_on_failures()
        return {"error": str(exc)}


async def execute_scheduled_run(ctx: dict, client_id: str, scheduler_run_id: str) -> None:
    """
    arq job — executes the full pipeline for one scheduled client run.
    Retries up to 3 times with exponential backoff on pipeline failure.
    """
    client_id_uuid = uuid.UUID(client_id)
    sr_id = uuid.UUID(scheduler_run_id)
    log = logger.bind(client_id=client_id, scheduler_run_id=scheduler_run_id)
    log.info("scheduled_run_starting")

    run_id: uuid.UUID | None = None

    # ── Phase 1: Create the pipeline Run row ──────────────────────────────────
    async with AsyncSessionLocal() as db:
        sr = (
            await db.execute(select(SchedulerRun).where(SchedulerRun.id == sr_id))
        ).scalar_one_or_none()
        if sr is None:
            log.error("scheduler_run_not_found")
            return

        sr.status = "started"
        sr.updated_at = _now()

        try:
            run = await start_run(client_id_uuid, db)
            sr.run_id = run.id
            run_id = run.id

            await log_audit(
                db,
                client_id=client_id_uuid,
                action="scheduled_run_started",
                entity_type="run",
                entity_id=run.id,
                actor="scheduler",
                details={"cadence": sr.cadence},
            )
            await db.commit()

        except ValueError as exc:
            # No active prompts — not retryable
            sr.status = "failed"
            sr.error_message = str(exc)
            sr.updated_at = _now()
            await db.commit()
            log.error("scheduled_run_no_prompts", error=str(exc))
            return

        except Exception as exc:
            sr.status = "failed"
            sr.error_message = f"Setup failed: {str(exc)[:300]}"
            sr.updated_at = _now()
            await db.commit()
            log.error("scheduled_run_setup_failed", error=str(exc))
            raise

    if run_id is None:
        return

    # ── Phase 2: Execute the pipeline ────────────────────────────────────────
    try:
        await run_pipeline(run_id, client_id_uuid, AsyncSessionLocal)

        async with AsyncSessionLocal() as db:
            async with db.begin():
                sr = (
                    await db.execute(select(SchedulerRun).where(SchedulerRun.id == sr_id))
                ).scalar_one()
                sr.status = "completed"
                sr.updated_at = _now()
                await log_audit(
                    db,
                    client_id=client_id_uuid,
                    action="scheduled_run_completed",
                    entity_type="run",
                    entity_id=run_id,
                    actor="scheduler",
                )

        log.info("scheduled_run_completed", run_id=str(run_id))

    except Exception as exc:
        log.error("scheduled_run_pipeline_failed", error=str(exc), run_id=str(run_id))

        retry_count = 0
        async with AsyncSessionLocal() as db:
            async with db.begin():
                sr = (
                    await db.execute(select(SchedulerRun).where(SchedulerRun.id == sr_id))
                ).scalar_one()
                sr.retry_count += 1
                retry_count = sr.retry_count
                if retry_count >= 3:
                    sr.status = "failed"
                    sr.error_message = str(exc)[:500]
                    sr.updated_at = _now()
                    await log_audit(
                        db,
                        client_id=client_id_uuid,
                        action="scheduled_run_failed",
                        entity_type="run",
                        entity_id=run_id,
                        actor="scheduler",
                        details={"error": str(exc)[:200], "retry_count": retry_count},
                    )
                else:
                    sr.status = "enqueued"
                    sr.updated_at = _now()

        if retry_count < 3:
            # Exponential backoff: 5 min, 10 min, give up
            raise Retry(defer=300 * (2 ** (retry_count - 1)))
